// This file is automatically generated. Do not edit it directly.
/* eslint-disable @typescript-eslint/no-explicit-any */
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { brokeredPreviewStorage } from "./previewAuthStorage";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const inMemoryTables: Record<string, any[]> = {
  trip_inquiries: [],
};

function createMockSupabaseClient(): any {
  return {
    auth: {
      getSession: async () => ({ data: { session: null }, error: null }),
      getUser: async () => ({ data: { user: null }, error: null }),
      onAuthStateChange: () => ({ data: { subscription: { unsubscribe: () => {} } } }),
      signInWithPassword: async () => ({ data: null, error: new Error("Supabase offline") }),
      signUp: async () => ({ data: null, error: new Error("Supabase offline") }),
      signOut: async () => ({ error: null }),
    },
    from: (tableName: string) => {
      if (!inMemoryTables[tableName]) {
        inMemoryTables[tableName] = [];
      }
      const tableData = inMemoryTables[tableName]!;

      const builder: any = {
        select: () => builder,
        order: () => builder,
        limit: () => builder,
        range: () => builder,
        single: () => {
          const item = tableData[0] || null;
          const promise = Promise.resolve({ data: item, error: null });
          return Object.assign(promise, builder);
        },
        maybeSingle: () => {
          const item = tableData[0] || null;
          const promise = Promise.resolve({ data: item, error: null });
          return Object.assign(promise, builder);
        },
        insert: (values: any) => {
          const rows = Array.isArray(values) ? values : [values];
          const newRows = rows.map((r) => ({
            id: `mock-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
            created_at: new Date().toISOString(),
            updated_at: new Date().toISOString(),
            status: "pending",
            ...r,
          }));
          tableData.push(...newRows);
          const promise = Promise.resolve({ data: newRows, error: null });
          return Object.assign(promise, builder);
        },
        update: (values: any) => {
          const promise = Promise.resolve({ data: values, error: null });
          return Object.assign(promise, builder);
        },
        delete: () => {
          const promise = Promise.resolve({ data: null, error: null });
          return Object.assign(promise, builder);
        },
        eq: () => builder,
        neq: () => builder,
        gt: () => builder,
        gte: () => builder,
        lt: () => builder,
        lte: () => builder,
        like: () => builder,
        ilike: () => builder,
        is: () => builder,
        in: () => builder,
        then: (onfulfilled?: (value: any) => any, onrejected?: (reason: any) => any) => {
          return Promise.resolve({ data: tableData, error: null }).then(onfulfilled, onrejected);
        },
      };

      return builder;
    },
  };
}

function createSupabaseClient() {
  // Use import.meta.env for client-side (Vite build-time replacement)
  // Fall back to process.env for SSR (server-side rendering)
  const SUPABASE_URL =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env["VITE_SUPABASE_URL"]
      : undefined) || (typeof process !== "undefined" ? process.env["SUPABASE_URL"] : undefined);
  const SUPABASE_PUBLISHABLE_KEY =
    (typeof import.meta !== "undefined" && import.meta.env
      ? import.meta.env["VITE_SUPABASE_PUBLISHABLE_KEY"]
      : undefined) ||
    (typeof process !== "undefined" ? process.env["SUPABASE_PUBLISHABLE_KEY"] : undefined);

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
    ];
    console.warn(
      `[Supabase] Missing environment variable(s): ${missing.join(", ")}. Using mock in-memory fallback.`,
    );
    return createMockSupabaseClient() as ReturnType<typeof createClient<Database>>;
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});
